pull_request_rules:
  - name: Automatic merge to master on successful build and test if it's not WIP
    conditions:
      - base=master
      - check-success=build
      - check-success=test
      - -title~=(?i)wip
    actions:
      merge:
        method: merge
      delete_head_branch:
      assign:
        add_users:
          - 5h15h4k1n9
  - name: Add `haskell` label, if files associated with Haskell were changed
    conditions:
      - files~=\.hs$
    actions:
      label:
        add:
          - haskell