name:                MSI
version:             0.0.2
github:              "5h15h4k1n9/MSI"
license:             BSD3
author:              "Roman Shishkin"
maintainer:          "romashkin.2001@yandex.ru"
copyright:           "2025 Roman Shishkin"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis:            Mini interpreter for Solidity
category:            Interpreter

description:         Please see the README on GitHub at <https://github.com/5h15h4k1n9/MSI#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - array
  - parsec
  - stm

library:
  source-dirs:
    - src
    - src/interpreter
    - src/parser

executables:
  msi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - MSI
