name:                MSI
version:             0.0.2
github:              "5h15h4k1n9/MSI"
license:             BSD3
author:              "Roman Shishkin"
maintainer:          "romashkin.2001@yandex.ru"
copyright:           "2022 Roman Shishkin"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis:            Mini interpreter for Solidity
category:            Interpreter

description:         Please see the README on GitHub at <https://github.com/5h15h4k1n9/MSI#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - hspec >= 2.7.8 && < 3
  - hspec-core >= 2.7.8 && < 3
  - hspec-discover >= 2.7.8 && < 3
  - hspec-expectations >= 0.8.2 && < 1
  - parsec
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src
    - src/interpreter
    - src/parser

executables:
  msi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - MSI

tests:
  msi-test:
    main:                Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - MSI
