name: Build and Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
          ghc-version: 8.10.4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            ~/.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Setup
        run: |
          stack --no-terminal setup

      - name: Build
        run: |
          stack --no-terminal build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
          ghc-version: 8.10.4

      - name: Test
        run: ./test/run.sh
