name: test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        enable-stack: true

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ~/.stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Setup
      run: | 
        stack --no-terminal setup

    - name: Build
      run: |
        stack --no-terminal build

    - name: Test
      run: stack --no-terminal test --test-arguments --color --coverage
